version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/webui/frontend"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
