package stats 

import (
	"time"
	"path/filepath"

	"github.com/Pegasus8/piworker/utilities/log"
	"github.com/Pegasus8/piworker/processment/data"
)

// StartLoop is the function used to start the loop used to work with
// the statistics generated by PiWorker and the Raspberry Pi where it's running.
func StartLoop(statsChannel chan Statistic, dataChannel chan data.UserData) {
	log.Infoln("Preparing to start stats loop...")

	log.Infoln("Preparing database...")
	db, err := InitDB(filepath.Join(SatisticsPath, DatabaseName))
	if err != nil {
		log.Criticalln(err)
	}
	defer db.Close()
	err = CreateTable(db)
	if err != nil {
		log.Criticalln(err)
	}
	log.Infoln("Database ready to work")

	log.Infoln("Starting stats loop...")
	for range time.Tick(1 * time.Second) {
		userData := <- dataChannel
		statistics, err := GetStatistics(&userData)
		if err != nil {
			log.Fatalln(err)
		}
		select {
		case statsChannel <- *statistics:
			// Sending data to channel
		default:
			// No receiver
		}

		StoreRasberryStatistics(db, statistics.RaspberryStats)
	}
}