package stats

import (
	// "path/filepath"
	"time"

	"github.com/rs/zerolog/log"
)

// StartLoop is the function used to start the loop used to work with
// the statistics generated by PiWorker and the Raspberry Pi where it's running.
// Returns the instance of the database with the purpose of be closed properly.
func StartLoop() {
	log.Info().Msg("Starting stats loop")

	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()

	for range ticker.C {
		if err := UpdateRPiStats(); err != nil {
			log.Panic().Err(err).Msg("Error when trying to update the rpi stats")
		}

		Current.RLock()
		if err := StoreStats(&Current.TasksStats, &Current.RaspberryStats); err != nil {
			log.Panic().Err(err).Msg("Error when trying to store stats on the db")
		}
		Current.RUnlock()
	}
}
