package configs

// Filename is the name of the configs file.
const Filename string = "configs.json"

// ConfigsPath is the path where the configs file wanna be saved
const ConfigsPath string = "./configs/"

// DefaultConfigs is the variable that contains the default configs generally 
// used when the config file not exists.
var DefaultConfigs = Configs{
	Behavior: Behavior{
		LoopSleep: 0.5,
	},
	Security: Security{
		DeniedIPs: []string{},
		LocalNetworkAccess: true,
	},
	APIConfigs: APIConfigs{
		NewTaskAPI: true,
		EditTaskAPI: true,
		DeleteTaskAPI: true,
		RequireToken: true,
		Token: "", // Need to be autogenerated 
	},
	Updates: Updates{
		DailyCheck: true,
		AutoDownload: true,
		BugsPrevention: true,
	},
	WebUI: WebUI{
		RequireToken: true,
		TokenToAccess: "", // Need to be autogenerated
 	},
}