# Example from https://github.com/reviewdog/action-golangci-lint
name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        # uses: docker://reviewdog/action-golangci-lint:v1 # pre-build docker image
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  # eslint:
  #   name: eslint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code into directory
  #       uses: actions/checkout@v1
  #     - name: cd to frontend path
  #       run: cd $GITHUB_WORKSPACE/webui/frontend
  #     - name: ESLint check
  #       uses: gimenete/eslint-action@1.0
